### ISSUE TITLE
A Need for inclusion of multilingual BERT.

### ISSUE THREAD

**Issue by alexvaca0** [explosion/spacy-transformers#104]
Currently multilingual BERT, available in Transformers, is not supported in spacy-transformers, and there is a need for its inclusion.

**Comment by TheEdoardo93** [comment]
I think the same as you!

> Currently multilingual BERT, available in Transformers, is not supported in spacy-transformers, and there is a need for its inclusion.

**Comment by kinoute** [comment]
Same here. Some multilingual models would be great.

**Comment by TheEdoardo93** [comment]
For french users, please keep up-to-date with NLG French pre-trained models [here](https://github.com/huggingface/transformers/pull/1822) :D

**Comment by dduong1** [comment]
using init_model would'nt work? have you try with CamemBert ? 
python examples/init_model.py --lang xx --name bert-base-multilingual-cased /path/to/model

**Comment by kurodenjiro** [comment]
Same as you , do you have expamle to work ?

**Comment by svlandeg** [comment]
Merging with Issue #81, see also @ines her comment in that thread about using `init_model`.
