### ISSUE TITLE
broken links on blog page 

### ISSUE THREAD

**Issue by waalge** [explosion/spacy-transformers#106]
The links to the model releases on 
https://explosion.ai/blog/spacy-transformers
are to v2.1. 
E.g 
https://github.com/explosion/spacy-models/releases/tag/de_trf_bertbasecased_lg-2.1.0
rather than 
https://github.com/explosion/spacy-models/releases/tag/de_trf_bertbasecased_lg-2.2.0

**Comment by ines** [comment]
Thanks – fixed! 👍
