### ISSUE TITLE
How to pretrain Bert model from spacy

### ISSUE THREAD

**Issue by kurodenjiro** [explosion/spacy-transformers#107]
I want to train bert-base-multilingual-uncased from spacy model , how can i do it ?

**Comment by linetcz** [comment]
Hello, do you have any update in this issue? 
I'm trying to re-train `en-trf-bertbaseuncased-lg` model with specific domain text with the command line
`python -m spacy pretrain -bs 512 ./data/reddit.jsonl en_trf_bertbaseuncased_lg ./vectors_reddit_trf/`
but I got: `ZeroDivisionError: integer division or modulo by zero`
However when I try to re-train `en_vectors_web_lg` with this command line
`python -m spacy pretrain -bs 512 data/reddit.jsonl en_vectors_web_lg vectors_reddit/`
It works.

**Comment by svlandeg** [comment]
Hi and sorry for the late follow-up. All of this should be significantly improved in the upcoming spaCy 3 release. You can have a sneak preview here: https://nightly.spacy.io/usage/embeddings-transformers. This page also includes a lot of new documentation around vectors, transformers and pretraining.

The new [config system](https://nightly.spacy.io/usage/training#config) should also make it easier for us to help debug if you run into specific errors. I hope you'll be able to give the release candidate a try, and let us know how you go!
