### ISSUE TITLE
Will GPU speed up computing the similarity?

### ISSUE THREAD

**Issue by amitjslearn** [explosion/spacy-transformers#109]
I am trying to compute the similarity for large paragraphs
```
x.similarity(y)
```
The above line is taking a long time to run for the entire dataset, will using the GPU speed up this process? If so, how to enable it or is it enabled by default?

**Comment by svlandeg** [comment]
You can run `spacy.prefer_gpu()`, which will use the GPU if it's available and if CUDA is properly installed (check with `nvcc --version`). If it can't find the GPU, it will run on CPU.

An other alternative is to use `spacy.require_gpu()` which will actually raise an error if the GPU is not accessible.

**Comment by RoelTim** [comment]
@amitjslearn, did you find out whether the GPU speeds up `x.similarity(y)`?
