### ISSUE TITLE
Can we do transfer learning and fine tuning without labels in an Unsupervised manner?

### ISSUE THREAD

**Issue by amitjslearn** [explosion/spacy-transformers#111]
Can we do transfer learning and fine-tuning without labels in an Unsupervised manner for finding the similarities between the text? The example mentioned in the README for Transfer Learning is for text classification but it has labels? Can I do it without labels for text classification and textual similarities?

**Comment by svlandeg** [comment]
Merging with Issue #7 - please see the discussion there!
