### ISSUE TITLE
What hardware do i need?

### ISSUE THREAD

**Issue by snape6666** [explosion/spacy-transformers#112]
Hi,
i was trying to train a bert model on my nvidia 2080 ti but got memory issues... I also have an 2070 super in my othre machine, if this would help?!

Is there a way to train a text-classification-tuning with the german bert model with only one 2080 ti (11GB ram)? What settings do you guys use?

**Comment by svlandeg** [comment]
@honnibal previously ran the `train_textcat.py` script successfully with the XLNet model on a Tesla V100. Note that long documents in your dataset may cause memory problems as well.

Referring to Issue #https://github.com/explosion/spacy-transformers/issues/48 where more tips and tricks are discussed.
