### ISSUE TITLE
[feature requests] backwards models

### ISSUE THREAD

**Issue by tsoernes** [explosion/spacy-transformers#115]
With FastAI's text classification library, you often train two models. one of which you input the reversed representation of the input. Come prediction time, you average the results of the two model.

Can I make a request for models pre-trained on backwards text?

**Comment by svlandeg** [comment]
While we provide some pretrained pipelines for general use-cases, I think this particular use-case is probably better suited for custom trained user models. It feels impractical for us to be publishing each pretrained pipeline twice just to have the reverse. 

It could make for an interesting project to run this training yourself though. With the new spaCy [config system](https://nightly.spacy.io/usage/training#config) you can make sure both training steps remain aligned with the same hyperparameters, and you could even create a custom [spaCy project](https://nightly.spacy.io/usage/projects) to coordinate everything. If you do decide to go that route, let us know how you go on the [discussions forum](https://github.com/explosion/spaCy/discussions)!
