### ISSUE TITLE
cannot load multi lingual bert

### ISSUE THREAD

**Issue by AlexandreMoulti** [explosion/spacy-transformers#122]
Hi

I tried to use the multi lingual bert but it does not manage to donwload it. Is it yet available ?

**Comment by svlandeg** [comment]
Hi @AlexandreMoulti, you can find an overview of the available pretrained models at https://github.com/explosion/spacy-transformers#-quickstart. Multi-lingual bert is not currently available as a pretrained model, but you should be able to create one yourself following the instructions detailed at https://github.com/explosion/spacy-transformers#loading-models-from-a-path. Have a look specifically at the [init_model.py](https://github.com/explosion/spacy-transformers/blob/master/examples/init_model.py) script and the discussion in Issue #81.

Merging with #81 to keep the discussion in one place!
