### ISSUE TITLE
Can I use this repository for Sentence Embedding?

### ISSUE THREAD

**Issue by ankush20m** [explosion/spacy-transformers#127]
Hi, I want sentence embedding for my domain-specific task to compute the Cosine-Similarity. Can this repository provide sentence embedding? or is the feature coming in the future?

**Comment by adrianeboyd** [comment]
No, the sentence embeddings produced by default `spacy-transformers` models may not be very useful. There are other tools that provide better support for sentence embeddings in particular. One that looks promising is: https://github.com/UKPLab/sentence-transformers
