### ISSUE TITLE
Why so strict requirement on the transformers package?

### ISSUE THREAD

**Issue by SebiSebi** [explosion/spacy-transformers#128]
The `requirements.txt` file mentions the following dependency:
* transformers>=2.0.0,<2.1.0

Is there any reason for which `transformers` >= 2.1.0 is not supported?

**Comment by adrianeboyd** [comment]
The transformers API can change in ways that break the model loading and serialization, so we don't want to include future/untested versions outside a very limited range. If you'd like to test an upcoming version of `spacy-transformers`, you can install the current `master` from source, which should support `transformers>=2.4.0,<2.6.0`.

The transformers models provided by spacy will no longer be compatible after this upgrade, but you can initialize your own models with `examples/init_model.py`.
