### ISSUE TITLE
RFE: allow automatic use of transformers models without conversion/repackaging

### ISSUE THREAD

**Issue by asterbini** [explosion/spacy-transformers#129]
I have noticed that the transformers package allows the automatic download and use of many formats and models developed by the community by just stating their ID (e.g. the 'camembert-base' model)
It would be very nice if spacy (through spacy-transformers) would allow the same without the need for repackaging/retraining the models.

**Comment by honnibal** [comment]
Yes this is planned. We're very close to a release that reworks a lot of the underlying stuff, so that the transformers are easier to work with, and so you can access the underlying config much more easily.

**Comment by asterbini** [comment]
Great! I am eager to use it!

**Comment by asterbini** [comment]
I see that while it's easy to use transformers.AutoModel (etc) to automatically fetch and load the models to be converted, a new _tokenizers.SerializableXXXTokenizer class is required for saving the tokenizer. Have you perhaps implemented a _tokenizers.SerializableCamembertTokenizer ? (I would like to try it on French texts)

**Comment by adrianeboyd** [comment]
Please try out `spacy-nightly` as a preview of how this is implemented in `spacy` v3.0 and `spacy-transformers` v1.0: https://nightly.spacy.io

There's a pretrained French pipeline that uses `camembert-base`: https://nightly.spacy.io/models/fr#fr_dep_news_trf
