### ISSUE TITLE
Plans for spaCy + Transformers (re thinc.ai )

### ISSUE THREAD

**Issue by honnibal** [explosion/spacy-transformers#133]
After launching the first versions of this library and listening to a lot of the feature requests, we concluded that working with transformers really needed better access to machine learning models than the API was making easy. The implementation was also awkward in several ways, especially the subclassing of components, different factory names, and the need to subclass the `Language` class.

To provide better Transformers support, we therefore went back and started making a lot of fixes to Thinc, as well as doing some redesigning of spaCy to make working with transformers-based pipelines better. This resulted in a near complete rewrite of Thinc, which we launched last week: https://thinc.ai 

We're now working on a `spacy-nightly` release that makes use of the new Thinc. Once the new system is in place, we'll also make a new version of this library to work with it.

The main advantages will be much easier configuration, better flexibility, and the ability to easily share one transformers model across a spaCy pipeline. For instance, here's an example configuration file that uses a BiLSTM model as a shared representation between a tagger and parser: https://github.com/explosion/spaCy/blob/develop/examples/experiments/ptb-joint-pos-dep/bilstm_tok2vec.cfg . We also have an example using a transformer model with Thinc, without spaCy: https://github.com/explosion/thinc/blob/master/examples/02_transformers_tagger_bert.ipynb

The config system, together with better clarity around the ML API in spaCy, will make it much easier to author your own models for spaCy. spaCy 3.0 will also feature improvements to the pipeline components to make it easier to develop your own components.

Here's what will happen with this library specifically:

* The subclasses to `Language`, `Tagger` and `EntityRecognizer` will no longer be necessary
* The `Tok2vec` subclass will be made much simpler
* The ML functions will be simpler, and will be based on a proper well-documented library (the new Thinc version)
* Experiments will be configured via the Thinc config system
* The token alignment will be improved
* The extension attributes for the alignment and the activations will remain.

**Comment by ZhuoruLin** [comment]
Hi @honnibal ! I have been using `spacy-transformers` for a month I actually find it pretty straightforward to use. The transformer wrappers in `thinc` works fine too. Thanks for developing the great tools. The main concern I have is

**Comment by aced125** [comment]
This looks awesome!!

In terms of transformers, I think a really big improvement would come off processing multiple sentences at once (I know I mentioned this already but will do again). Transformers have been shown to be excellent at detecting long-range interactions.

I think transformers will become more and more popular as time passes (especially as text generation with transformers become better) and so it's great that you guys (along with HuggingFace) are leading the charge in terms of putting them into production.

Keep it up guys!

**Comment by svlandeg** [comment]
With the recent release of the `v1.0.0rc0` version of this library, compatible with [spaCy v3's pre-release](https://pypi.org/project/spacy-nightly/3.0.0rc1/), I think we can close this issue? :-)

The documentation of the new features is summarized on https://nightly.spacy.io/usage/embeddings-transformers and https://nightly.spacy.io/api/transformer. You can also find more information about spaCy v3's config system at https://nightly.spacy.io/usage/training#config, and a more general overview of what's new in 3.0 here: https://nightly.spacy.io/usage/v3

Have fun, and let us know what you think if you give the new version a spin!
