### ISSUE TITLE
Install problem: Requirements not satisfiable 

### ISSUE THREAD

**Issue by scottcode** [explosion/spacy-transformers#134]
When I try to `pip install spacy-transformers` I get the following error. 

```
ERROR: Could not find a version that satisfies the requirement torch>=1.0.0 (from spacy-transformers->-r xxxxx\condaenv.yagfu249.requirements.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.0.0 (from spacy-transformers->-r xxxxx\condaenv.yagfu249.requirements.txt (line 1))
```

For some reason pip cannot find a version of `torch>=1.0.0` that works with the bare-bones environment I created (specified below). 

```
> conda env export
name: spacytrf
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - openssl=1.1.1d=he774522_3
  - pip=20.0.2=py38_1
  - python=3.8.1=h5fd99cc_1
  - setuptools=45.1.0=py38_0
  - sqlite=3.31.1=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py38_0
  - wincertstore=0.2=py38_0
```

**Comment by svlandeg** [comment]
Sorry for the late reply. I think I ran into a similar issue once before, and I ended up installing pytorch following the instructions from the official site here: https://pytorch.org/get-started/locally/

Could you give that a try?

**Comment by svlandeg** [comment]
Clarified this in the docs, cf PR #118

**Comment by scottcode** [comment]
@svlandeg Thanks for the pointer and for adding it to the README. 

It seems that just the `pip install spacy-transformers` in a pristine environment didn't work, but making sure pytorch was already installed _**before**_ doing pip succeeded. I accomplished this with the following conda enviornment specification file and the following command

```
# environment.yml
name: spacytransformer
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - cpuonly
  - pip
  - pip:
      - spacy-transformers
```
Command:  
`conda env create -f environment.yml`
