### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement spacy-transformers (from versions: none)

### ISSUE THREAD

**Issue by bhargavvader** [explosion/spacy-transformers#140]
Hello, similar to #110 , I get this when I run ```pip install spacy-transformers``` .

```
ERROR: Could not find a version that satisfies the requirement spacy-transformers (from versions: none)
ERROR: No matching distribution found for spacy-transformers
```

Other packages work fine, and I have the latest pip running, and this is on a fresh virtualenv. My internet is working fine too.
Any idea what it could be?

**Comment by isabeauoliveri** [comment]
same problem

**Comment by adrianeboyd** [comment]
Hi, can you provide more information about your environment? How is your virtual environment set up? Could you provide the information from `spacy info --markdown` and `pip freeze`?

**Comment by Xinxin-Lai** [comment]
Hey, I have the same problem , anyone could help?

**Comment by svlandeg** [comment]
Could you try installing pytorch from the [official site](url) and then try again?  Probably best to do all of this in a clean environment. 

If you still run into issues, please provide the additional information Adriane asked about, to help debug what could be wrong.
