### ISSUE TITLE
Adding tagger, parser, ner in spacy_transformers pipeline

### ISSUE THREAD

**Issue by debanjanbhucs** [explosion/spacy-transformers#143]
In this tutorial - https://explosion.ai/blog/spacy-transformers it's written that you could also add spaCy's tagger, parser and entity recognizer to the pipeline. But I am unable to do so. I might be doing it wrong. Here is what I am doing:
`
import spacy
nlp = spacy.load("en_trf_bertbaseuncased_lg")
nlp.add_pipe(nlp.create_pipe("tagger"), last=True)
nlp.add_pipe(nlp.create_pipe("parser"), last=True)
nlp.add_pipe(nlp.create_pipe("ner"), last=True)

doc = nlp("SpaCy is awesome")
`

This results in the following output.
`
Traceback (most recent call last):
  File "examples.py", line 25, in <module>
    doc = nlp("Raymond is a brilliant chinese NLP researcher.")
  File "somepath/lib/python3.7/site-packages/spacy/language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "pipes.pyx", line 396, in spacy.pipeline.pipes.Tagger.__call__
  File "pipes.pyx", line 408, in spacy.pipeline.pipes.Tagger.predict
  File "pipes.pyx", line 86, in spacy.pipeline.pipes.Pipe.require_model
ValueError: [E109] Model for component 'tagger' not initialized. Did you forget to load a model, or forget to call begin_training()
`
I would like to know the correct way to do this. 
In case there is no such way it would be nice to add it.
Thanks!

**Comment by svlandeg** [comment]
The error messages gives a clue: The component is not initialized. Can you try calling `nlp.begin_training()` before using your `nlp` object ?

**Comment by Ershov-Alexander** [comment]
@svlandeg I tried `nlp.begin_training()`
Code:
```
import spacy

nlp = spacy.load("en_trf_bertbaseuncased_lg")
nlp.begin_training()
nlp.add_pipe(nlp.create_pipe("tagger"), last=True)
nlp.add_pipe(nlp.create_pipe("parser"), last=True)
nlp.add_pipe(nlp.create_pipe("ner"), last=True)

doc = nlp("SpaCy is awesome")
```

Result:
```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-1-5b798a7d6be4> in <module>
      7 nlp.add_pipe(nlp.create_pipe("ner"), last=True)
      8 
----> 9 doc = nlp("SpaCy is awesome")

~/PycharmProjects/dids/venv/lib/python3.7/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
    433             if not hasattr(proc, "__call__"):
    434                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 435             doc = proc(doc, **component_cfg.get(name, {}))
    436             if doc is None:
    437                 raise ValueError(Errors.E005.format(name=name))

pipes.pyx in spacy.pipeline.pipes.Tagger.__call__()

pipes.pyx in spacy.pipeline.pipes.Tagger.predict()

pipes.pyx in spacy.pipeline.pipes.Pipe.require_model()

ValueError: [E109] Model for component 'tagger' not initialized. Did you forget to load a model, or forget to call begin_training()?
```

Also, I tried to use pipes from `en_core_web_sm` model

Code:
```
import spacy

nlp = spacy.load("en_trf_bertbaseuncased_lg")
nlp2 = spacy.load("en_core_web_sm")

nlp.add_pipe(nlp2.tagger, last=True)
nlp.add_pipe(nlp2.parser, last=True)
nlp.add_pipe(nlp2.pipeline[2][1], last=True)

doc = nlp("SpaCy is awesome")
```

Result:
```
---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

<ipython-input-1-249e887156a2> in <module>
      8 nlp.add_pipe(nlp2.pipeline[2][1], last=True)
      9 
---> 10 doc = nlp("SpaCy is awesome")

~/PycharmProjects/dids/venv/lib/python3.7/site-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
    433             if not hasattr(proc, "__call__"):
    434                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
--> 435             doc = proc(doc, **component_cfg.get(name, {}))
    436             if doc is None:
    437                 raise ValueError(Errors.E005.format(name=name))

nn_parser.pyx in spacy.syntax.nn_parser.Parser.__call__()

nn_parser.pyx in spacy.syntax.nn_parser.Parser.set_annotations()

nonproj.pyx in spacy.syntax.nonproj.deprojectivize()

nonproj.pyx in spacy.syntax.nonproj.deprojectivize()

strings.pyx in spacy.strings.StringStore.__getitem__()

KeyError: "[E018] Can't retrieve string for hash '8206900633647566924'. This usually refers to an issue with the `Vocab` or `StringStore`."
```

**Comment by svlandeg** [comment]
You need to specify `nlp.begin_training()` after you've created the entire pipeline, i.e. after you're done adding components to it.

What `begin_training` will do, is initalize each component in the pipeline.

**Comment by debanjanbhucs** [comment]
As suggested by  Ershov-Alexander , I could not get any results even after having nlp.begin_training() after adding all the components to the pipeline.

**Comment by debanjanbhucs** [comment]
It doesn't throw any errors though. It is trying to train the taggers, which I don't want to. I just want to use the already trained taggers on my text.

```
import spacy

nlp = spacy.load("en_trf_bertbaseuncased_lg")

nlp.add_pipe(nlp.create_pipe("tagger"), last=True)
nlp.add_pipe(nlp.create_pipe("parser"), last=True)
nlp.add_pipe(nlp.create_pipe("ner"), last=True)
nlp.begin_training()

doc = nlp("New Delhi is the capital of India.")

for entity in doc.ents:
    print(entity.text)
```

**Comment by debanjanbhucs** [comment]
Also the following code:

```
import spacy

nlp = spacy.load("en_trf_bertbaseuncased_lg")
nlp2 = spacy.load("en_core_web_lg")

nlp.add_pipe(nlp2.tagger, last=True)
nlp.add_pipe(nlp2.parser, last=True)
nlp.add_pipe(nlp2.pipeline[2][1], last=True)
nlp.begin_training()

doc = nlp("New Delhi is the capital of India.")

for entity in doc.ents:
    print(entity.text)
```

throws KeyError

```
Traceback (most recent call last):
  File "/Users/dmahata/SentimentAggregateAnalytics/misc-utils/spacy-transformers/examples.py", line 57, in <module>
    doc = nlp("New Delhi is the capital of India.")
  File "/Users/dmahata/SentimentAggregateAnalytics/misc-utils/news-ke/.news-ke/lib/python3.7/site-packages/spacy/language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "nn_parser.pyx", line 234, in spacy.syntax.nn_parser.Parser.__call__
  File "nn_parser.pyx", line 374, in spacy.syntax.nn_parser.Parser.set_annotations
  File "nonproj.pyx", line 133, in spacy.syntax.nonproj.deprojectivize
  File "nonproj.pyx", line 138, in spacy.syntax.nonproj.deprojectivize
  File "strings.pyx", line 136, in spacy.strings.StringStore.__getitem__
KeyError: "[E018] Can't retrieve string for hash '7037928807040764755'. This usually refers to an issue with the `Vocab` or `StringStore`."
```

**Comment by svlandeg** [comment]
The misunderstanding here is that the `create_pipe()` function provides you with an already trained component. I'm afraid it doesn't. It literally creates a new pipeline component, which isn't yet initialized or trained. If you keep it like that in the pipeline and call `nlp()`, it won't work.

So basically what you want to do, is to first create and train those components you want to train (let's call it `nlp1`). Then after all that is done, you can do something like this:

```
nlp2 = spacy.load("en_core_web_md")    # this is a pretrained model, cf https://spacy.io/usage/models
tagger = nlp2.get_pipe("tagger")
nlp1.add_pipe(tagger)
```

After that you don't have to call `begin_training` anymore. You should just be able to use `nlp1(text)`. Let me know if that works for you!

**Comment by adrianeboyd** [comment]
It's a bit mixed in with other loading questions, but the basic approach is discussed in https://github.com/explosion/spaCy/issues/4768 and https://github.com/explosion/spaCy/issues/4812. You want to try to follow how `Language.from_disk/from_bytes` initialize components. You can probably simplify a bit of the path issues by using `to_bytes/from_bytes` instead.

I'm not 100% sure everything with the vectors from the spacy model is going to work out correctly when combined like this? If the spacy model has vectors, you want that vocab to be the base vocab (or the vectors will be missing) and then load the transformers components. I'm still not sure whether it will work as expected, though...

**Comment by svlandeg** [comment]
The recent release of `spacy-transformers` `v1.0.0rc0` brings compatibility with the pre-release of spaCy v3, currently available as [`spacy-nightly`](https://pypi.org/project/spacy-nightly/). This makes the library more robust for use-cases like the one described in this thread. Here is some detailed documentation on how to share Transformer weights across different components: https://nightly.spacy.io/usage/embeddings-transformers

There's also a new approach to source components from existing pipelines, cf https://nightly.spacy.io/usage/processing-pipelines#sourced-components. 

If you would be able to give the new version a spin, we'd love to hear your feedback! And ofcourse let us know if you run into any issues.
