### ISSUE TITLE
Unable to install: ERROR: Could not find a version that satisfies the requirement torch>=1.0.0

### ISSUE THREAD

**Issue by erotavlas** [explosion/spacy-transformers#145]
I'm getting this error when I run the 

`pip install spacy-transfomers`

from a new conda environment (also I'm on a Windows 10 machine if that matters)

> 
> ERROR: Could not find a version that satisfies the requirement torch>=1.0.0 (from spacy-transformers) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
> ERROR: No matching distribution found for torch>=1.0.0 (from spacy-transformers)

**Comment by svlandeg** [comment]
You'll have to install pytorch using the instructions from the official site here: https://pytorch.org/get-started/locally/. Hope that works - if not, let us know!

**Comment by svlandeg** [comment]
Clarified this in the docs, cf PR #118

**Comment by erotavlas** [comment]
Thanks for the quick reply.  
It is working for me after I installed pytorch.

**Comment by svlandeg** [comment]
Happy to hear it!
