### ISSUE TITLE
Spacy model package for GPT-2

### ISSUE THREAD

**Issue by JainSameer06** [explosion/spacy-transformers#146]
Is there a Spacy model package for GPT-2?

If not, how can I use pretrained weights from a GPT-2 model with spacy-transformers? Example code to do this would be quite helpful, since most of the examples in the demo notebook use Spacy's pre-packaged models.

**Comment by adrianeboyd** [comment]
You can use this example script to create a spacy model from a pretrained transformers model:

https://github.com/explosion/spacy-transformers/blob/111667c14fc26b36eff20f551e1981c09bcfd7ca/examples/init_model.py

The main limitation is that it needs to use a tokenizer that `spacy-transformers` supports (currently Bert, DistilBert, GPT2, XLM, XLNet, Roberta). `gpt2` as a pretrained model is definitely supported.

**Comment by JainSameer06** [comment]
This works! Thank you!
