### ISSUE TITLE
Could not load en_trf_bertbaseuncased_lg

### ISSUE THREAD

**Issue by jiawang1990** [explosion/spacy-transformers#151]
en_trf_bertbaseuncased_lg could not be installed in my local 
even with spacy-transformers installed 
it complains Can't import language trf from spacy.lang: No module named 'spacy.lang.trf'

One more weird thing is that version of spacy-transformers becomes 0.0.0 after I downloaded en_trf_bertbaseuncased_lg

**Comment by jiawang1990** [comment]
I have found out the reason... spacy-transformers said setuptools is required at any version but it is actually required latest version

**Comment by adrianeboyd** [comment]
Thanks for posting your solution! What was the older version you were using that didn't work correctly?

**Comment by jiawang1990** [comment]
@adrianeboyd 28... sth
