### ISSUE TITLE
Use huggingface transformer models with spacy-transformers

### ISSUE THREAD

**Issue by SRITANU** [explosion/spacy-transformers#153]
I am using huggingface's bert-large-uncased model with 1024-H. Is there a way that I can make it work with spacy-transformers? spacy-transformers uses Google's bert base model with 768-H.

The reason for using spacy-transformers with the above-mentioned model is to make use of the token alignment b/w the wordpiece and spacy tokenization and consequently the weighted sum of the aligned tokens.

**Comment by SRITANU** [comment]
Closing the issue. Figured it out. Was in the docs but way down below.
For anybody who missed it out in the README, here it is. Download the bert-large-uncased-model. Extract it. It contains the json and bin file. But you also need the vocab.txt file in the folder.

```
name = "bert-large-uncased"
path = "/home/sritanu/Documents/Upwork/bert-large-uncased/"
nlp = TransformersLanguage(trf_name=name, meta={"lang": "en"})
nlp.add_pipe(nlp.create_pipe("sentencizer"))
nlp.add_pipe(TransformersWordPiecer.from_pretrained(nlp.vocab, path))
nlp.add_pipe(TransformersTok2Vec.from_pretrained(nlp.vocab, path))

doc = nlp("Here is some text to encode.")
```

**Comment by svlandeg** [comment]
Thanks for clarifying the solution!
