### ISSUE TITLE
load models camemBERT or flauBERT

### ISSUE THREAD

**Issue by x0rzkov** [explosion/spacy-transformers#158]
Hi guys,

Hope you are all well !

Is it possible to load into spacy-transformers models like [camemBERT](https://camembert-model.fr/) or [flauBERT](https://github.com/getalp/Flaubert) for sentiment analysis ?

Thanks for any input or insights.

Cheers,
X

**Comment by svlandeg** [comment]
Yes, you should be able to load any model from the HuggingFace transformers library.

I think there are two ways in which you can use e.g. [camemBERT](https://huggingface.co/transformers/model_doc/camembert.html) in a spaCy pipeline. You can load the [bare CamemBERT Model](https://huggingface.co/transformers/model_doc/camembert.html#camembertmodel) that outputs raw hidden states, and use this as the `Transformer` component in a spaCy pipeline. Other components in the pipeline (like a `textcat`) could then be trained on top of this language model, fine-tuning it to your specific task, e.g. sentiment analysis. For more information on this use-case, see the documentation of spaCy v3 here: https://nightly.spacy.io/usage/embeddings-transformers

Alternatively, you could pick one of the camemBERT models with a pretrained head, like [CamembertForMultipleChoice](https://huggingface.co/transformers/model_doc/camembert.html#camembertformultiplechoice), and use the full pre-trained model as the `textcat` component in your pipeline, by using [Thinc's PyTorch wrapper](https://thinc.ai/docs/api-layers#pytorchwrapper). See here for more documentation: https://nightly.spacy.io/usage/layers-architectures#frameworks.

Both use-cases should be much better supported now that `v1.0.0rc0` version of this library has been released (just recently) and works with the pre-release of spaCy v3 (https://pypi.org/project/spacy-nightly/3.0.0rc1/). Let us know if you run into specific problems though!
