### ISSUE TITLE
Inconsistent tokenizer between spacy and spacy transformer

### ISSUE THREAD

**Issue by lamthuy** [explosion/spacy-transformers#159]
Hi,
When we try to tokenize the following sentence:

If we use spacy 

```
a = spacy.load('en_core_web_lg')

doc = a("I like the link http://www.idph.iowa.gov/ohds/oral-health-center/coordinator")

list(doc)
```

We got

```
[I, like, the, link, http://www.idph.iowa.gov, /, ohds, /, oral, -, health, -, center, /, coordinator]
```

But if we use the Spacy transformer tokenizer:
```
a = spacy.load(en_trf_bertbaseuncased_lg')

doc = a("I like the link http://www.idph.iowa.gov/ohds/oral-health-center/coordinator")

list(doc)
```
we got:
```
[I, like, the, link, http://www.idph.iowa.gov/ohds/oral-health-center/coordinator]
```
The main reason was that the version of spacy model is 2.2.5 while the version of spacy transformer is 2.2.0. Is there any chance to upgrade the spacy transformer model to 2.2.5?

**Comment by adrianeboyd** [comment]
The quickest way is to copy the `tokenizer` file in the model directory from one model to the other. This should work between any v2.2.x models for spacy and spacy-transformers.

Then the tokenizer settings will then be the same for both models, but be careful to use the same version of spacy everywhere or you might see slightly different behavior across v2.2 versions, especially from v2.2.1 to v2.2.2, where some of the tokenizer regex priorities were changed a bit to handle some edge cases. This was a mistake, especially in a patch release, and the plan is to go back to something closer to v2.2.1 in v2.3.
