### ISSUE TITLE
ShapeMismatchError while trying to fine-tune model with TransformersEntityRecognizer

### ISSUE THREAD

**Issue by zweili** [explosion/spacy-transformers#164]
Hi,
My main goal is to fine-tune bioBERT model for NER task on a custom datasets.
I wanted to try first with a simple dataset and few labels (taken from an example on spacy website).
But i have an error while running this code:

```
import random
from spacy.gold import GoldParse
from spacy.util import minibatch
from spacy_transformers import TransformersLanguage, TransformersWordPiecer, TransformersTok2Vec, TransformersEntityRecognizer

name = "pytorch_model"
path = "/content/biobert/pytorch_model"

nlp = TransformersLanguage(trf_name=name, meta={"lang": "en"})

nlp.add_pipe(nlp.create_pipe("sentencizer"))
nlp.add_pipe(TransformersWordPiecer.from_pretrained(nlp.vocab, path))
nlp.add_pipe(TransformersTok2Vec.from_pretrained(nlp.vocab, path))

ner = TransformersEntityRecognizer(nlp.vocab)

for label in [ "ORG", "GPE", "PRODUCT", "LOC"]:
  ner.add_label(label)

nlp.add_pipe(ner)

train_data = [
    ("Uber blew through $1 million a week", [(0, 4, 'ORG')]),
    ("Android Pay expands to Canada", [(0, 11, 'PRODUCT'), (23, 30, 'GPE')]),
    ("Spotify steps up Asia expansion", [(0, 8, "ORG"), (17, 21, "LOC")]),
    ("Google Maps launches location sharing", [(0, 11, "PRODUCT")]),
    ("Google rebrands its business apps", [(0, 6, "ORG")]),
    ("look what i found on google! 😂", [(21, 27, "PRODUCT")])]

optimizer = nlp.resume_training()
for itn in range(100):
    random.shuffle(train_data)
    for batch in minibatch(train_data, size=8):
        raw_text, entity_offsets = zip(*batch)
        docs_ = [nlp(txt) for txt in raw_text]
        golds_ = [GoldParse(doc, entities=entity) for doc, entity in zip(docs_, entity_offsets)]
        ner.update(docs_, golds_, drop=0.5, sgd=optimizer)
nlp.to_disk("/content/pt_spacytrans_model")`
```

I get this error:
---------------------------------------------------------------------------

> ShapeMismatchError                        Traceback (most recent call last)
> <ipython-input-77-d5e9cbca4cf2> in <module>()
>       8     for batch in minibatch(train_data, size=8):
>       9         raw_text, entity_offsets = zip(*batch)
> ---> 10         docs_ = [nlp(txt) for txt in raw_text]
>      11         golds_ = [GoldParse(doc, entities=entity) for doc, entity in zip(docs_, entity_offsets)]
>      12         ner.update(docs_, golds_, drop=0.5, sgd=optimizer)
> 
> 6 frames
> <ipython-input-77-d5e9cbca4cf2> in <listcomp>(.0)
>       8     for batch in minibatch(train_data, size=8):
>       9         raw_text, entity_offsets = zip(*batch)
> ---> 10         docs_ = [nlp(txt) for txt in raw_text]
>      11         golds_ = [GoldParse(doc, entities=entity) for doc, entity in zip(docs_, entity_offsets)]
>      12         ner.update(docs_, golds_, drop=0.5, sgd=optimizer)
> 
> /usr/local/lib/python3.6/dist-packages/spacy/language.py in __call__(self, text, disable, component_cfg)
>     437             if not hasattr(proc, "__call__"):
>     438                 raise ValueError(Errors.E003.format(component=type(proc), name=name))
> --> 439             doc = proc(doc, **component_cfg.get(name, {}))
>     440             if doc is None:
>     441                 raise ValueError(Errors.E005.format(name=name))
> 
> nn_parser.pyx in spacy.syntax.nn_parser.Parser.__call__()
> 
> nn_parser.pyx in spacy.syntax.nn_parser.Parser.predict()
> 
> nn_parser.pyx in spacy.syntax.nn_parser.Parser.greedy_parse()
> 
> /usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/model.py in __call__(self, x)
>     165             Must match expected shape
>     166         """
> --> 167         return self.predict(x)
>     168 
>     169     def pipe(self, stream, batch_size=128):
> 
> /usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/model.py in predict(self, X)
>     129 
>     130     def predict(self, X):
> --> 131         y, _ = self.begin_update(X, drop=None)
>     132         return y
>     133 
> 
> _parser_model.pyx in spacy.syntax._parser_model.ParserModel.begin_update()
> 
> _parser_model.pyx in spacy.syntax._parser_model.ParserStepModel.__init__()
> 
> /usr/local/lib/python3.6/dist-packages/thinc/neural/_classes/feed_forward.py in begin_update(self, X, drop)
>      44         callbacks = []
>      45         for layer in self._layers:
> ---> 46             X, inc_layer_grad = layer.begin_update(X, drop=drop)
>      47             callbacks.append(inc_layer_grad)
>      48 
> 
> /usr/local/lib/python3.6/dist-packages/thinc/check.py in checked_function(wrapped, instance, args, kwargs)
>     153                 if not isinstance(check, Callable):
>     154                     raise ExpectedTypeError(check, ["Callable"])
> --> 155                 check(arg_id, fix_args, kwargs)
>     156         return wrapped(*args, **kwargs)
>     157 
> 
> /usr/local/lib/python3.6/dist-packages/thinc/check.py in has_shape_inner(arg_id, args, kwargs)
>      72             # Allow underspecified dimensions
>      73             if dim is not None and arg.shape[i] != dim:
> ---> 74                 raise ShapeMismatchError(arg.shape, shape_values, shape)
>      75 
>      76     return has_shape_inner
> 
> ShapeMismatchError: 
> 
>   Shape mismatch: input (8, 1024) not compatible with [None, 768].
> 
>   Traceback:
>   ├─ __call__ in /usr/local/lib/python3.6/dist-packages/spacy/language.py:439
>   ├─── __call__ in neural/_classes/model.py:167
>   └───── predict in neural/_classes/model.py:131
>          >>> y, _ = self.begin_update(X, drop=None)

Thank you for your help!

**Comment by svlandeg** [comment]
Hi, apologies for the late follow-up. We have recently revamped this library and released a `v1.0.0rc0` version, which I think should be much more robust and easier to use. It works together with spaCy v3, for which a pre-release is available as [`spacy-nightly`](https://pypi.org/project/spacy-nightly/).

With spaCy v3, you should be able to use the [train CLI](https://nightly.spacy.io/api/cli#train) instead of custom train scripts, as the CLI now takes a [config file](https://nightly.spacy.io/usage/training#config) that allows you to customize a lot of the settings according to your specific use-case. The support for transformers should be much more robust; you can find the documentation at https://nightly.spacy.io/usage/embeddings-transformers#transformers and https://nightly.spacy.io/api/transformer. 

It would be great if you could give this a spin, and let us know how you go!
