### ISSUE TITLE
Assertion error when training Multi-class Distilbert Classifer.

### ISSUE THREAD

**Issue by NeuroWinter** [explosion/spacy-transformers#166]
Hello all I really love this library so far, however I ran into this issue today after around 5 hours of training:

```---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-eb2c9b2f4a2f> in <module>()
----> 1 main('en_trf_distilbertbaseuncased_lg', input_dir=Path("./in/"), output_dir=Path("./out/"), batch_size=4)
<ipython-input-2-a95003bdd481> in main(model, input_dir, output_dir, n_iter, n_texts, batch_size, learn_rate, max_wpb, use_test, pos_label)
    112             optimizer.trf_lr = next(learn_rates)
    113             texts, annotations = zip(*batch)
--> 114             nlp.update(texts, annotations, sgd=optimizer, drop=0.1, losses=losses)
    115             # pbar.update(1)
    116             if step and (step % eval_every) == 0:
~/anaconda3/envs/python3/lib/python3.6/site-packages/spacy_transformers/language.py in update(self, docs, golds, drop, sgd, losses, component_cfg)
    106                 sgd=sgd,
    107                 losses=losses,
--> 108                 component_cfg=component_cfg,
    109             )
    110         backprop_tok2vec(docs, sgd=sgd)
~/anaconda3/envs/python3/lib/python3.6/site-packages/spacy/language.py in update(self, docs, golds, drop, sgd, losses, component_cfg)
    517             kwargs = component_cfg.get(name, {})
    518             kwargs.setdefault("drop", drop)
--> 519             proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
    520             for key, (W, dW) in grads.items():
    521                 sgd(W, dW, key=key)
pipes.pyx in spacy.pipeline.pipes.TextCategorizer.update()
~/anaconda3/envs/python3/lib/python3.6/site-packages/thinc/neural/_classes/feed_forward.py in begin_update(self, X, drop)
     44         callbacks = []
     45         for layer in self._layers:
---> 46             X, inc_layer_grad = layer.begin_update(X, drop=drop)
     47             callbacks.append(inc_layer_grad)
     48 
~/anaconda3/envs/python3/lib/python3.6/site-packages/spacy_transformers/model_registry.py in get_last_hidden(docs, drop)
    240     for out in outputs:
    241         assert out is not None
--> 242         assert out.size != 0
    243 
    244     def backprop_last_hidden(d_outputs, sgd=None):
AssertionError:
```

My `main` function is based off the train_textcat.py example, with a few changes, mainly the evaluate function, and the removal of tqdm as I was having issues with it in my notebook. 

Another thing to note is that I was getting good results when using MCC as my evaluation stat, but my losses were though the roof, last successful evaluation step was: 
`Losses: 46.756 MCC: 0.705`.

This is using the latest pip `spacy[cuda100] (2.2.4) and spacy-transformers (0.5.1 )`

Any help would be much appreciated. 

- Neuro

**Comment by NeuroWinter** [comment]
Has anyone had a chance to look at this yet ?

**Comment by svlandeg** [comment]
Apologies for the late follow-up. I'm not exactly sure what may be going on in your example. We did streamline the [training CLI](https://nightly.spacy.io/api/cli#train) a lot in spaCy v3, for which a a pre-release is available as [`spacy-nightly`](https://pypi.org/project/spacy-nightly/). You can now use a custom [config file](https://nightly.spacy.io/usage/training#config) which should eliminate (hopefully) the need for these custom training scripts like `train_textcat.py` that we had before. This library has also matured a lot, and a `v1.0.0rc0` version is now available to work with spaCy v3. We'd love to hear your feedback on this, and hope that your issues will be solved when you upgrade to this more stable version! But please do let us know if you run into any trouble.

**Comment by NeuroWinter** [comment]
Thank you for the update @svlandeg I will look into spaCy v3 :)
