### ISSUE TITLE
doc.tensor assign non-zero vectors to token that exceed maximum length

### ISSUE THREAD

**Issue by ZhuoruLin** [explosion/spacy-transformers#176]
Hi @adrianeboyd ,

I noticed some issues in alignment.

From README of this project:

> Many of the pretrained transformer models have a maximum sequence length. If a sentence is longer than the maximum, it is truncated and the affected ending tokens will receive zeroed vectors.

But this is not how `doc.tensor` behaves. Please refer to the mini example below:

```
import spacy
import spacy_transformers
from spacy_transformers.language import TransformersLanguage
from spacy_transformers.pipeline.wordpiecer import TransformersWordPiecer
from spacy_transformers.pipeline.tok2vec import ATTRS, get_sents, TransformersTok2Vec, _get_boundary_sensitive_alignment

text = "Life is wonderful. Spacy is awesome!"*100

nlp = TransformersLanguage(meta={"lang":"en"})

wordpiecer = TransformersWordPiecer.from_pretrained(nlp.vocab, 'distilbert-base-uncased')
tok2vec = TransformersTok2Vec.from_pretrained(nlp.vocab, 'distilbert-base-uncased')

nlp.add_pipe(wordpiecer)
nlp.add_pipe(tok2vec)

doc = nlp(text)

print(len(doc)) # Should be 602

print(doc.tensor[-1]) # Nonzero
```

And this is due to the fact that in https://github.com/explosion/spacy-transformers/blob/bf729718502053ac9bd8770fc67aaeb549593510/spacy_transformers/pipeline/tok2vec.py#L208-L225

line 222 would assign an `align_sizes` that equals the length of the sentence to the sentence 
boundary tokens. But instead, we should add the length of the alignment that includes word pieces that do not exceed the maximum length limit.

I had a branch to fix this. But I noticed that `spacy-transformers` is under complete rewrite. Is it still worth making a pull-request?

Please take a look and tell me what's your opinion.

Thank you for your time!

**Comment by adrianeboyd** [comment]
Hmm, on the one hand that looks like a bug, but on the other, I'm not actually sure what the desired behavior is here given the conflicting comments / docs.

**Comment by ZhuoruLin** [comment]
Hi @adrianeboyd . Sorry for my English :( 

 So for a sentence with more than 512 wordpieces, those tokens with that exceed the maximum length should receive a zero vector in `doc.tensor`. But they are still assigned with non-zero vectors right now. And this is due to `_get_boundary_sensitive_alignment` assign `wp_rows` and `align_sizes`. I actually have [this branch](https://github.com/bomboradata/spacy-transformers/tree/bugfix/boundary_sensitive_alignment) that resolves this issue. You might understand me better if you just look at the one-line fix.

**Comment by adrianeboyd** [comment]
When I was looking at the truncation behavior I went by the inline comments (align the boundary tokens to every token) rather than the README (have zero vectors for tokens after truncation limit).

I'm just not familiar enough with transformers to know what the desired behavior should be.

**Comment by vriesdemichael** [comment]
While I get that there should be some discussion about how sentences that exceed the maximum length are treated, it is currently preventing processing large documents with a sentence exceeding the maximum size.

As a dirty hotfix for my own project I added another pipeline action after the sentencizer which sets `is_sent_start` on the first token exceeding the maximum sentence length, this creates unnatural sentences where they exceed the maximum length, but enabled me to still process the docs. 

I would like to see a more permanent solution in this package.

**Comment by svlandeg** [comment]
Thanks @ZhuoruLin for the constructive discussion! Apologies that we haven't had the time to look into your fix in more detail. The library has been significantly rewritten and released today as v.1.0. If the issue still persists in the new version, feel free to open a PR to discuss further. 

General support is being moved to the spaCy repo though. That means that new bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or discussions can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions). Thanks!
