### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement spacy-transformers 

### ISSUE THREAD

**Issue by yw2903** [explosion/spacy-transformers#179]
I got the following error by installing spacy-transformers. 
```
ERROR: Could not find a version that satisfies the requirement spacy-transformers (from versions: none)
ERROR: No matching distribution found for spacy-transformers 
```

Spacy is most up-to date.

**Comment by svlandeg** [comment]
This may be happening because of a failed torch installation.

Could you try installing pytorch from the [official site](url) and then try again?  Probably best to do all of this in a clean environment.

**Comment by yw2903** [comment]
Still got the same error after successfully installing torch. 

```
Collecting torch
  Downloading torch-1.4.0-cp27-cp27mu-manylinux1_x86_64.whl (753.4 MB)
     |████████████████████████████████| 753.4 MB 2.8 MB/s
Installing collected packages: torch
Successfully installed torch-1.4.0
```

**Comment by svlandeg** [comment]
Are you working in a clean virtual environment? Could you provide the output from running `python -m spacy info --markdown`?  And the full log of the console (command+output) when the error is thrown?
