### ISSUE TITLE
Error calculating word pieces for sentences.

### ISSUE THREAD

**Issue by ab3llini** [explosion/spacy-transformers#193]
Hi,

While trying to use this amazing library with an Italian pre-trained instance of **BERT** ([dbmdz/bert-base-italian-xxl-uncased](https://huggingface.co/dbmdz/bert-base-italian-xxl-cased)) we experienced a **ValueError**. We believe this error applies to **any instance of BERT**, no matter the language because it is bound to the model capacity (512 in this case).

After further investigation, we discovered that it is due to the length of the spacy document. In our case we were working with a document totaling **2209** tokens. After the TransformersWordPiecer call, these tokens get converted to **2555** word-piece tokens ready for BERT input.

It looks like after the maximum model sequence length capacity is reached (**512** for **BERT**) the word-piece token alignments are not being computed at all, resulting in an Exception being raised in `wordpiecer.py`,  within `set_annotations()`. 

**You can replicate this issue** by taking any **Italian** document long enough (i.e. with its word-piece representation longer than 512 - 2 tokens) and running the following snippet:

```
from spacy_transformers import TransformersLanguage, TransformersWordPiecer, TransformersTok2Vec

doc = open('document.txt').read()

name = "dbmdz/bert-base-italian-xxl-uncased"

nlp = TransformersLanguage(trf_name=name, meta={"lang": "it"})
nlp.add_pipe(nlp.create_pipe("sentencizer"))
nlp.add_pipe(TransformersWordPiecer.from_pretrained(nlp.vocab, name))
nlp.add_pipe(TransformersTok2Vec.from_pretrained(nlp.vocab, name))

nlp(doc)  # Crashes if doc word pieces are more than 510 (512 - 2)

```

Please note that if the document is shorter, everything works fine.
For the time being, we found a workaround by manually chopping the document into smaller pieces and calling the pipeline manually, but we would **really love** to have this fantastic library account for longer documents on its own.

Thank you, you are amazing.

**Comment by adrianeboyd** [comment]
If you're interested, you can try installing from source to test the fix (this will be released as v0.5.3 soon):

```
pip install https://github.com/explosion/spacy-transformers/archive/v0.5.x.zip
```

Feedback is appreciated if you run into any errors!

**Comment by ab3llini** [comment]
It works fine, but there is another minor problem: when I install the lib it downgrades the transformers library from 2.11.0 to 2.0.0, breaking my whole project.

**Comment by ab3llini** [comment]
Hi @adrianeboyd, I just wanted to inform you that 0.5.3 forces me to use transformers 2.0.0, but I need the latest one (2.11.0). Can you fix that too? By the way, we tested even 6.0.0 but it lacks your changes and keeps on crashing.

**Comment by ab3llini** [comment]
Then, there is a further issue with model naming:

Within the lib you switch config depending on the name of the model. 
We are using an official model from hugging face repo named **dbmdz/bert-base-italian-xxl-uncased**

Apparently, that **dbmdz/** prefix breaks the loginc within the lib

**Comment by adrianeboyd** [comment]
If you upgrade to spacy-transformers v0.6.1, it should support "dbmdz/bert-base-italian-xxl-uncased", which isn't supported in v0.5.x. Unfortunately due to changes in transformers, spacy-transformers v0.6.1 only supports up to transformers v2.8.0.

spacy-transformers v0.6.1 should include the same changes related to truncation as v0.5.3. (Please don't use v0.6.0, it has some major bugs.)
