### ISSUE TITLE
Alignment issue after upgrade to 0.6.1

### ISSUE THREAD

**Issue by ZhuoruLin** [explosion/spacy-transformers#203]
Hi @adrianeboyd ,

I hope everything is doing well. 

I recently noticed a wordpiecer issue after upgrade to a recent release of `spacy-transformers==0.6.1` when I tried to apply `spacy-transformers` in my project. Please refer to the following mini example:
 
```
from spacy_transformers.language import TransformersLanguage
from spacy_transformers.pipeline.wordpiecer import TransformersWordPiecer, ATTRS
import pandas as pd

nlp = TransformersLanguage(meta={"lang":"en"})
wordpiecer = TransformersWordPiecer.from_pretrained(nlp.vocab, trf_name="distilbert-base-uncased")
nlp.add_pipe(wordpiecer)

bug_text = "Christmas is coming, but many family members won't get to spend this time face to face. Millions will be placing phone calls, and another large number will be hopping on Skype. The latest update adds more ways to integrate Skype into your holiday plans. One option is to send a winter-themed video card. Tap on the + button in the lower right followed by the snowflake. You can then share your creation via Skype, a social network, or email. To spread the gift further, you are now able to send video messages to more than one person at once. Your recordings can go as high as 720p. If you're not sending your Christmas cheer through video, you can still spice things up with holiday emoji. New options include a Christmas tree, Santa, a polar bear, and a monkey making a snow angel. I'm not an emoji guy, but I'm still particularly fond of that last one. Skype has also rolled out the ability to send Skype credit as a gift. You can do so at skype.com/send.credit. What's New: Create your holiday video card. Tap on the button on the lower right, then tap on the snowflake to record, and share over Skype, social networks, or e-mail. Send video messages to groups. Create a new video message and select the people you want to send it to, or record and send in a group chat. ❝my neighbor's aunty is making $98 HOURLY on the internet❞....A few days ago new McLaren F1 subsequent after earning 18,512$,,,this was my previous month's paycheck ,and-a little over, $17k Last month ..3-5 h/r of work a day ..with extra open doors & weekly paychecks.. it's realy the easiest work I have ever Do.. I Joined This 7 months ago and now making over $87, p/h.Learn More right Here... za....... ➤➤. ➤➤➤ http://GlobalSuperEmploymentVacanciesReportJobs/GetPaid/$98hourly...❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦.❦"

doc = nlp.make_doc(bug_text)

wordpiecer(doc)
```

and this would returns error:
```
ValueError: Error calculating word pieces for sentences. Total number of wordpieces in the doc was 512, but adding up the wordpieces for its sentences we get 510. This means there's a bug in the extension attributes or the tokenizer.add_special_tokens() logic, often when a spaCy sentence aligns against 0 wordpieces.
```

I can confirm that this error would not show up in `spacy-transformers==0.5.3`. 

The reason for this error is because the `TransformersWordPiecer.align` method would produce alignment that skips wordpieces. If you do `wordpieces, alignment = wordpiecer.predict([doc])`, the output alignment looks like this:

```
...[507], [], [509], [], [], ...
```
which skips our last wordpiece that is before the `max_len` cut: 510. The result is leading the `spacy_transformers.language.get_wp_end` to return 509 instead of 510 and detect the wrong boundary.

I don't know whether this is due to the existence of unicode characters in my example but it does look like it.

Please help me out :(. I appreciate it!

**Comment by adrianeboyd** [comment]
The main change here would be from #123. Try reverting that commit to see if it makes a difference?

**Comment by ZhuoruLin** [comment]
@adrianeboyd Yeah I did revert to 0.5.3 that doesn't contain this commit and it solves the issues on this particular case.

**Comment by svlandeg** [comment]
This should be fixed in the new v. 1.0 release, which can be used together with spaCy v. 3.0. So I think we can close this.

New bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions).

Thanks for testing the early prereleases of this package! All the feedback has been really helpful :-)
