### ISSUE TITLE
Huge pipeline bottleneck caused by repeated model config I/O ops. 

### ISSUE THREAD

**Issue by ab3llini** [explosion/spacy-transformers#204]
Hello,

We are heavily using this library in our project.
While for short documents it is perfect, we are experiencing enormous slowdowns on larger documents (approximately 700 sentences).

We deeply investigated the architecture and discovered a **heavy bottleneck** within the pipeline.
Bypassing the bottleck allowed roughly **60x speed boost** in our scenario (from 10 minutes to 10 seconds using `distillbert`)

I will try to explain the issue as clear as possible:

**Context**

Library version: `0.6.1`
Transformers version: `2.8.0`
Transformer model in use: `distilbert-base-multilingual-cased`

**Code snippet**

```
bert_model = 'distilbert-base-multilingual-cased'

nlp = TransformersLanguage(trf_name=bert_model, meta={"lang": "it"})
nlp.add_pipe(nlp.create_pipe("sentencizer"))
nlp.add_pipe(TransformersWordPiecer.from_pretrained(nlp.vocab, bert_model))
nlp.add_pipe(TransformersTok2Vec.from_pretrained(nlp.vocab, bert_model))

doc = nlp(raw_doc)
```

**The issue**

Within `spacy_transformers/util.py`, function `get_segment_ids()`, line `284` there is the following call:
`name = get_config_name(name)`

The latter instruction induces an I/O operation to access the model configuration and obtain context-specific information.
The problem is that it is called for every sentence in the document, hence for a document with 1000 sentences you perform 1000 I/O operations. 

We are using an instance of `distilbert`, and replacing with `name = 'distilbert'` lead to blazing-fast performances. Otherwise, the execution looks idle: no CPU nor GPU is used due to the bottleneck and the processing takes minutes to run (if not hours).

I hope you could find a way to cache the configuration once, and use it multiple times (a singleton maybe?)

Thanks in advance.
Alberto

**Comment by honnibal** [comment]
Wow, that's embarrassing! Thanks for the report and analysis. I hope we can have a fix out quickly, ideally this week. Hopefully you can make the patch locally in the meantime?

**Comment by ab3llini** [comment]
Thanks for your help @honnibal! You are awesome!
We look forward to the release of 0.6.2 with the fixes. Meanwhile, we'll pull the latest fixes manually :)

**Comment by honnibal** [comment]
@ab3llini I've just deployed the v0.6.2 version. Thanks again for the report.
