### ISSUE TITLE
Converting and Repackaging other models

### ISSUE THREAD

**Issue by igorbrigadir** [explosion/spacy-transformers#206]
I would like to test out https://huggingface.co/huggingface/prunebert-base-uncased-6-finepruned-w-distil-squad but would like to keep the same model loading and packaging as the existing `spacy-transformers` models like `en_trf_distilbertbaseuncased_lg`. 

I'm still not sure what steps are involved in packaging an existing model like this - is there any documentation or another way of loading the model? Will this have to wait until #173 is merged?

This is related to #129 but rather than automatic use i'll settle for instructions on how to go about it for the current version.

I could rewrite my own stuff to use transformers library directly but i'd prefer to keep using spacy-transformers because it makes things simpler to deploy.

**Comment by adrianeboyd** [comment]
If you save the model to disk, you can load it from the directory with `spacy.load("/path/to/model")`.

If you want to package this saved model as a python package that you can install with `pip`, you can use the spacy CLI command `spacy package`. You'll probably want to adjust the metadata in `meta.json` before packaging. See the details at: https://spacy.io/api/cli#package

**Comment by igorbrigadir** [comment]
i think i figured it out: 

Directly loading the directory is not enough it seems - for https://huggingface.co/huggingface/prunebert-base-uncased-6-finepruned-w-distil-squad for example, it comes packaged in this kind of directory: 

File name | 
-- |
config.json | 
pytorch_model.bin | 
special_tokens_map.json | 
tf_model.h5 | 
tokenizer_config.json | 
vocab.txt | 

Which spacy can't load with `spacy.load("/path/to/model")`

But using this example https://github.com/explosion/spacy-transformers/blob/master/examples/init_model.py which i missed earlier, worked for me:

Running: 

`model_init.py prunebert-base-uncased-6-finepruned-w-distil-squad`

Downloaded the model, and converted `prunebert-base-uncased-6-finepruned-w-distil-squad` into something spacy can load from a directory.

After that, the `spacy package` command will work i presume - i didn't test it because it's enough for me to load it from a directory, don't need a pip installable package.

I think there is still a good bit of work in getting the pruned version of the model to load like this example https://github.com/huggingface/transformers/blob/master/examples/movement-pruning/Saving_PruneBERT.ipynb but that's maybe a separate thing for later.

**Comment by adrianeboyd** [comment]
Ah, sorry, I thought you were a step further and had already created the spacy model directory. The script `examples/init_model.py` is the right way to create a directory with the model that can be loaded with `spacy.load()` and then you could package that with `spacy package` if you'd like.

As of v0.6.1, you can supply a name like ` huggingface/prunebert-base-uncased-6-finepruned-w-distil-squad` to the `-n` 
argument and it should auto-detect the remaining settings.

No, you don't want to try out the version with recent PR yet. That's work in progress for the upcoming spacy v3 and is a total rewrite of this wrapper.

**Comment by igorbrigadir** [comment]
Yep, that's exactly it. Thanks! I got the latest `v0.6.2` working, and looking forward to trying out the new v3 release later.
