### ISSUE TITLE
Issues using spacy's nlp.evaluate() with spacy-transformer's trf_textcat

### ISSUE THREAD

**Issue by MarveM** [explosion/spacy-transformers#207]
Hi,

I hope this is the right place to ask, apologies if I have missed anything. I have previously used this library for a binary classification, following the examples, and it worked really well for me, thank you!

I am now re-visiting a multi label classification problem. Previoulsy, using spacy's textcat with the 'en_core_web_lg' model I achieved good results, but wanted to see how much of an improvement I can achieve by swapping the models and using the 'en_trf_bertbaseuncased_lg' model instead. The provided evaluate example function for the trf_textcat example code would not work for a multi-label problem, but spacy's nlp.evaluate works beautifully for textcat, I was hoping as spacy-transformers integrates so well with other components of spacy, I could also use it for trf_textcat?

However, when using:

**scores = nlp.evaluate(eval_data)**

All the scores are empty:
**print(scores.scores)**
**{'uas': 0.0, 'las': 0.0, 'las_per_type': {'': {'p': 0.0, 'r': 0.0, 'f': 0.0}}, 'ents_p': 0.0, 'ents_r': 0.0, 'ents_f': 0.0, 'ents_per_type': {}, 'tags_acc': 0.0, 'token_acc': 100.0, 'textcat_score': 0.0, 'textcats_per_cat': {}}**

At first I thought there was an issue with the labels, but this looks correct to me:

**nlp = spacy.load('en_trf_bertbaseuncased_lg')
textcat = nlp.create_pipe('trf_textcat')
nlp.add_pipe(textcat, last=True)
print(nlp.pipe_names)
['trf_wordpiecer', 'trf_tok2vec', 'trf_textcat'

for label in cats:
    textcat.add_label(label)

print(len(textcat.labels))
23**

It seems that nlp.evaluate only works for textcat? Is there a way to match this up with trf_textcat, or is a custom function the only way to do this at the moment? Apologies for the lazy question, I am still new to all of this so was hoping to rely on nlp.evaluate to handle multi label problems more adequately than I would manage at a first attempt with a custom function.

Many thanks!

**Comment by svlandeg** [comment]
Hi! Sorry for the late reply, but we've been working on a revamped version of this library, which has recently been released as `v1.0.0rc0`. This new version works together with the pre-release of spaCy v3: https://nightly.spacy.io

In a nutshell, the new version doesn't make a distinction anymore between `textcat` and `trf_textcat`. Instead, transformers can be much more closely integrated with your typical spaCy pipeline by just [swapping out](https://nightly.spacy.io/usage/embeddings-transformers#training-custom-model) a "normal" `Tok2Vec` layer and replacing it with a Transformer. This works for any component that takes a `tok2vec` component - not just `textcat`. But the nice thing is that everything else stays the same, so I would assume that your issue with scoring is resolved in this new version. If you can give it a spin, let us know how you go!
