### ISSUE TITLE
mean instead of sum for doc and span vectorisation

### ISSUE THREAD

**Issue by tim-jagenberg-ws** [explosion/spacy-transformers#225]
The span and doc vectorisation in `tok2vec.py` uses `sum` for doc and span:
`return doc.tensor.sum(axis=0)` and `return span.doc.tensor[span.start : span.end].sum(axis=0)`

This leads to longer docs or spans having higher-magnitude vector representations:
```
sample1 = nlp("Yes or no?")
sample2 = nlp("The quick brown fox jumps over the lazy dog")
print(np.linalg.norm(sample1.vector))
print(np.linalg.norm(sample2.vector))
```
```
72.27918
166.95401
```

Using `mean` for vectorisation will lead to comparable vectors also across varying doc/span lengths:
```
print(np.linalg.norm(sample1.tensor.mean(axis=0)))
print(np.linalg.norm(sample2.tensor.mean(axis=0)))
```
```
18.069796
18.550446
```

**Comment by svlandeg** [comment]
I think your approach makes sense, and I think you have the data you need for this workaround from the `tensor` attribute, so I hope that works for you.

We've just recently revamped this whole library and released a `v1.0.0rc0` version. From v1 onwards, the `Transformer` component sets its data in the `doc._.trf_data` attribute, but you can also provide an additional callback [`set_extra_annotations`](https://nightly.spacy.io/api/transformer#config) to set additional information on the `Doc` objects. So you should be able to customize this however you want, using the new config system of spaCy v3, for which a a pre-release is available as [`spacy-nightly`](https://pypi.org/project/spacy-nightly/).

More information can be found at https://nightly.spacy.io/usage/embeddings-transformers#transformers and https://nightly.spacy.io/api/transformer.
