### ISSUE TITLE
spacy-transformers install on conda

### ISSUE THREAD

**Issue by jack-rory-staunton** [explosion/spacy-transformers#227]
After successfully following the instructions on installing spacy with conda, the following conda install of spacy transformers shows:

(spacy3) analytics@ces-3660f9bed5e4a3a952b17d4e5ef5196b:~$ conda install -c conda-forge spacy-transformers
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - spacy-transformers

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by adrianeboyd** [comment]
Hi, `spacy-transformers` is currently only available through `pip`. It's just a source package, so I would hope the install in the conda env is pretty straightforward? I would install spacy and torch first with `conda` so their dependencies are installed through `conda` (follow the quickstart in the pytorch docs for conda), but I think `transformers` and `spacy-transformers` should be fine through `pip`. (Actually, that's not quite true. It looks like you could potentially run into problems with `sentencepiece`.)

In any case, it doesn't look like there are `conda-forge` `transformers` releases for the version range supported by the current `spacy-transformers` 0.6.x, so `pip` is your best bet.

**Comment by jack-rory-staunton** [comment]
OK. Shouldn't the conda installation instructions of spacy-transformers be removed from the documentation then?

**Comment by adrianeboyd** [comment]
Sorry, where is it in the documentation?

**Comment by jack-rory-staunton** [comment]
admittedly hard to find 

![image](https://user-images.githubusercontent.com/55473618/96460990-d4ce1c00-11f1-11eb-94e8-21488ba953d0.png)

**Comment by jack-rory-staunton** [comment]
Oh I see now the comment about "only available via pip" - not sure if that applies to the spacy-transformers or not though.

**Comment by adrianeboyd** [comment]
Ah, that's not where I looked to check, either. We'll get that updated, thanks!

**Comment by jack-rory-staunton** [comment]
thanks Adriane!

**Comment by adrianeboyd** [comment]
Yes, `spacy-nightly` is only through `pip` because there's no good prerelease mechanism on `conda-forge` (as far as we can tell, anyway). But we need to update this because `spacy-transformers` and `spacy-lookups-data` aren't on `conda-forge`.

**Comment by adrianeboyd** [comment]
Okay, a bit of a delay, but this is updated on the website now. We decided to just remove the `conda` option entirely for `nightly` so this is less confusing.
