### ISSUE TITLE
Loading Fine-Tuned model for NER

### ISSUE THREAD

**Issue by polodealvarado** [explosion/spacy-transformers#233]
Hello everyone!

I would like to know what function should I take from spacy-transformers to load the NER part into my pipeline using my fine-tuned BERT model.

**Comment by svlandeg** [comment]
Hi! Could you be a little more specific as to what you're trying to do, and what isn't working?

Are you working with the (release candidate of) spaCy v3? This library has been revamped for spaCy 3 and now gives much more control on how to use Transformers in a standard spaCy pipeline. You can't just load an NER model in though - you'll have to train it specifically on top of your fine-tuned BERT model.

A good place to start are the docs for spaCy 3 (currently available as `spacy-nightly`:
- https://nightly.spacy.io/usage/embeddings-transformers
- https://nightly.spacy.io/usage/training
- https://nightly.spacy.io/usage/processing-pipelines

**Comment by polodealvarado** [comment]
Sure!

I have my fine-tuned transformer model for Name Entity Recognition already trained to identify 6 different entities.
Could it be possible to use it with the new Spacy 3.0 pipeline ?
