### ISSUE TITLE
OSError: [E050] Can't find model 'en_trf_bertbaseuncased_lg

### ISSUE THREAD

**Issue by louisabraham** [explosion/spacy-transformers#234]
On colab: <https://colab.research.google.com/drive/1sqp6gav8w_7ZnPQ-Kx37Xm3NU3fQjJpa>

```py
!python -m spacy download en_trf_bertbaseuncased_lg
import spacy
nlp = spacy.load("en_trf_bertbaseuncased_lg")
```

My fix is to use the full path: `spacy.load("/usr/local/lib/python3.6/dist-packages/en_trf_bertbaseuncased_lg/en_trf_bertbaseuncased_lg-2.3.0")`

I can also do
```py
import en_trf_bertbaseuncased_lg
en_trf_bertbaseuncased_lg.load()
```

**Comment by adrianeboyd** [comment]
Hi, this is an issue with the notebook environment. You need to restart the runtime for python to register the newly-installed model package, and then you can load it just from the package name.

**Comment by louisabraham** [comment]
Thanks!

IMO (but I don't mind using my fix), it should be possible to do it without restarting the kernel (for example using importlib since `import en_trf_bertbaseuncased_lg` works).

**Comment by adrianeboyd** [comment]
The spacy v2 code is still maintaining compatibility with python 2.7, so I don't think we could use `importlib`, although that may make it easier if we want to update this in spacy v3.

If you'd like to have a look, it's `is_package()` in `spacy.util`. A PR would be welcome!
