### ISSUE TITLE
 No compatible package found for 'en_trf_bertbaseuncased_lg' (spaCy v3.0.0rc2)

### ISSUE THREAD

**Issue by NightFallLegacy** [explosion/spacy-transformers#244]
In Google Colab when I run the command:
`!python -m spacy download en_trf_bertbaseuncased_lg`

I get the following error:
`2020-12-31 20:09:26.366429: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1

✘ No compatible package found for 'en_trf_bertbaseuncased_lg' (spaCy
v3.0.0rc2)`

I have all of the requirements installed as well.
This issue only arises when I try to use the BERT model not the "en_core_web_trf" model

**Comment by adrianeboyd** [comment]
This model package only exists for spacy v2, not spacy v3. The `en_core_web_trf` model is the most similar v3 model available. Available models are currently described here: https://nightly.spacy.io/models

If you want a similar `bert-base-uncased` model, you can run `spacy init config` for `en` and replace the transformer model in the config with the one you'd like to use. You can use any model that's loadable with `AutoModel.from_pretrained()`, either a model name in the huggingface models database or a local path.
