### ISSUE TITLE
How to load models without vocab.json?

### ISSUE THREAD

**Issue by mcPear** [explosion/spacy-transformers#252]
Hi, I struggle to use xml-roberta-base https://huggingface.co/xlm-roberta-base/tree/main. 
I tried with v0.6.x but couldn't load to spacy due to missing vocab.json. And with nightly release of spacy transformers I don't know how to provide nlp.vocab in this code snippet:
`trf = Transformer(
    nlp.vocab,
    TransformerModel(
        "bert-base-cased",
        get_spans=get_doc_spans,
        tokenizer_config={"use_fast": True},
    ),
    set_extra_annotations=null_annotation_setter,
    max_batch_items=4096,
)`
Is it possible at all?

**Comment by adrianeboyd** [comment]
This kind of workflow is one of the main differences in v3. The construction from the class in possible, but afterwards you can't add it to a pipeline, so there aren't very many cases where you'd want to do it like this. `nlp.add_pipe` now takes the string name instead of the component object, so that it knows all the details about the config required to create the component and can save/reload the config and the component correctly.

Instead, pass the config settings as part of `add_pipe` if you're initializing this way (for most cases we'd recommend using a config file instead, though):

```python
nlp.add_pipe("transformer", config=config)
```

Then it's automatically initialized with the right vocab. See: https://nightly.spacy.io/api/transformer

**Comment by mcPear** [comment]
Thank you very much! Now, where to get `nlp` from? Should it be "empty" one? I just want to pass some text through transformer to get contextualized word vectors.

**Comment by adrianeboyd** [comment]
Yes, a blank model is fine:

```python
import spacy
from spacy_transformers import Transformer

nlp = spacy.blank("en")
nlp.add_pipe("transformer") # default config with roberta-base
# or: nlp.add_pipe("transformer", config=config)
nlp.initialize()

doc = nlp("This is a sentence.")
print(doc._.trf_data)
```

**Comment by mcPear** [comment]
Thanks again! Which lang should I pass to `spacy.blank(lang)` to use with multilang [xml-roberta-base](https://huggingface.co/xlm-roberta-base/tree/main)?

**Comment by adrianeboyd** [comment]
That just depends on how you want your spacy docs tokenized. The most generic option is `xx`, but that doesn't handle languages without whitespace between words at all. We don't have a multilingual tokenizer that can handle both English and Chinese, for example.

**Comment by mcPear** [comment]
Hi again, sorry for delay. I have tried it but still can't get embeddings. Code:
`import spacy
from spacy_transformers import Transformer

config = {
    "model": {
        "@architectures": "spacy-transformers.TransformerModel.v1",
        "name": "xlm-roberta-base",
        "tokenizer_config": {"use_fast": True}
    }
}

nlp = spacy.blank("xx")
nlp.add_pipe("transformer", config=config)
nlp.initialize()

doc = nlp("This is a sentence.")`

Doc's `tensor` and `vector` are empty arrays. `doc._.trf_data.tensors` are filled but how to make it working with `similarity` method?

**Comment by svlandeg** [comment]
In the new version 1.0, the transformer data is being set in `Doc._.trf_data` by default, but you can specify a `set_extra_annotations` to store the data any way you like, cf https://nightly.spacy.io/api/transformer#set_annotations

We're going to be closing this issue tracker and move the support to spaCy's repo instead. For additional questions or help with coding, feel free to post on our [community discussions forum](https://github.com/explosion/spaCy/discussions)!
