### ISSUE TITLE
Loss in Spacy_Transformers_Demo

### ISSUE THREAD

**Issue by deeplaunch** [explosion/spacy-transformers#45]
Thank you very much for creating the [tutorial](https://github.com/explosion/spacy-pytorch-transformers/blob/master/examples/Spacy_Transformers_Demo.ipynb)!

When I try to replicate it on colab with GPU, loss keeps increasing. Also there is no significant improvement in F-score according to the following output (for Bert and XLnet). Is this result expected?

![Capture](https://user-images.githubusercontent.com/33491823/63786598-58c39700-c8c0-11e9-869e-0ab266316730.JPG)

**Comment by honnibal** [comment]
Humble thanks to @kayvane for that --- it's really helpful!

I think the results there look reasonably expected?
