### ISSUE TITLE
CUDA out of memory with batch size 1, word per batch 1 and 12GB of GPU memory

### ISSUE THREAD

**Issue by tsoernes** [explosion/spacy-transformers#48]
I'm running the text classifier with the english `BERT` model, but always get out of memory, even though I've got `batch_size=1`, `words_per_batch=1`, and have `11441MiB` of GPU memory. This is with
```
spacy                      2.1.8           
spacy-pytorch-transformers 0.3.0
```
on CUDA10. Any suggestions? (The OOM error happens during `nlp.update`, not evaluation)

**Comment by honnibal** [comment]
The `words_per_batch` won't divide a long document up into multiple updates, so if you have a long document that could still be causing problems. How many words is your longest document?

**Comment by tsoernes** [comment]
The longest doc is `1743890` characters and `42918` tokens (by the `en_core_web_lg` tokenizer`). So that's the problem then.

**Comment by tsoernes** [comment]
@honnibal Provided that I've pruned the longest documents; what approach do you recommend in general, reducing batch size or words per batch?

**Comment by tsoernes** [comment]
Also. Should using `make_sentence examples` help reduce RAM usage? And if you use it; should you do the same at test time / production usage and average over predictions?

**Comment by honnibal** [comment]
The sentence batching and words-per-batch mechanisms reduce memory usage a bit, but only so much.

Basically, if you think about how the transformer models work, you end up with memory requirements in `N**2` for the attention matrices. On long documents, that will be the dominant memory cost. Computing over the sentences means that `N` is smaller, but you still have to hold the gradients for each sentence in memory.

I think you would probably run out of memory on a 40k word document, even with the per-sentence computation trick. So yeah you'll need to prune those. After pruning the long documents, you can experiment with the batch size. The transformers do need a reasonable batch size to get accurate gradients, so you might have to do gradient accumulation if you're still running out of memory. 

You might want to try the experimental training helper here: https://github.com/explosion/spacy-pytorch-transformers/blob/master/spacy_pytorch_transformers/_train.py . It supports gradient accumulation. Example usage here: https://github.com/explosion/spacy-pytorch-transformers/blob/tmp/examples/tasks/_glue2.py#L173

**Comment by honnibal** [comment]
The `make_sentence_examples` can definitely help reduce memory usage, yes. It makes it much easier to have batches which have consistent numbers of words, because you don't need to update over whole documents.

Depending on your classifier architecture, you don't necessarily need to do anything special at test time. The default is to just mean-pool the logits and run the softmax. This should be mostly the same as averaging the sentence predictions.

If you want to make it exactly the same, just swap the order of the mean pool and the softmax, like this:

```python

@register_model("softmax_last_hidden_pool_first")
def softmax_last_hidden_pool_first(nr_class, *, exclusive_classes=True, **cfg):
    width = cfg["token_vector_width"]
    return chain(
        get_pytt_last_hidden,
        flatten_add_lengths,
        with_getitem(0, Softmax(nr_class, width)),
        Pooling(mean_pool)
    )
```

I realise the layer definitions are a bit obscure, but: the `flatten_add_length` layer takes a list of arrays and turns them into a tuple `(data, lengths)` -- basically a ragged array format. The `with_getitem` is a wrapper that takes a layer, and applies it to an item of a tuple. It then inserts the result of the layer into the output. So `with_getitem(0, layer)` is the same as doing:

```
X = inputs[0]
Y = layer(X)
outputs = (Y, inputs[1:])
```

**Comment by tobiascornille** [comment]
I'm trying to train BERT for text classification like in https://github.com/explosion/spacy-transformers/blob/v0.6.x/examples/train_textcat.py

However I always seem to run out of GPU memory. I "only" have 8 GB at my disposal (GeForce RTX 2070), but even when I set my batch size to 1 I almost immediately run out of memory. I've tried clearing the torch cache, but this doesn't really solve the issue. The texts I'm training on are maybe 200-300 words long, but this shouldn't be unmanageable, or is it?

Are there other pointers you can provide to help me train?
Another question: is it normal that just loading the BERT model takes about 2GB of GPU memory already?

**Comment by svlandeg** [comment]
Apologies for the late follow-up. This library has been significantly rewritten and published today as v. 1.0. We'll publish the corresponding spaCy v. 3.0 very soon as well 🥳 

It would be great if you could update your scripts and let us know how you go on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions). Bugs can be posted on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues). 

Thanks for testing the early prereleases of this package! All the feedback has been really helpful :-)
