### ISSUE TITLE
Which metrics for comparing vector similarities?

### ISSUE THREAD

**Issue by wuqui** [explosion/spacy-transformers#65]
First of all, thanks a lot for this extension, having access to BERT via spaCy in such a convenient way is just amazing! I have tried to find all of this in your documentation, but there are a couple of things I couldn't find out:

1. Does `doc.similarity` return the cosine similarity value? I've read that this can be problematic with BERT embeddings: [1] Do you still think it's valid it to make claims about how semantically similar two docs/toks are? Some people seem to prefer Euclidian distance over cosine similarity. 

2. `doc.vector` should give me the vector representation of the whole document, right? Which measure is behind the vector returned? Is this e.g. the mean of all the token vectors in the doc? And if I want to lump together a couple of documents to get a vector representation for the whole bunch, is it valid to take the mean of the document vectors or would you recommend a different measure?

3. Is it possible to retrieve the n closest neighbour tokens/documents of a target tok/doc?

[1]: https://github.com/hanxiao/bert-as-service#q-the-cosine-similarity-of-two-sentence-vectors-is-unreasonably-high-eg-always--08-whats-wrong

**Comment by amitjslearn** [comment]
> First of all, thanks a lot for this extension, having access to BERT via spaCy in such a convenient way is just amazing! I have tried to find all of this in your documentation, but there are a couple of things I couldn't find out:
> 
> 1. Does `doc.similarity` return the cosine similarity value? I've read that this can be problematic with BERT embeddings: [1](https://github.com/hanxiao/bert-as-service#q-the-cosine-similarity-of-two-sentence-vectors-is-unreasonably-high-eg-always--08-whats-wrong) Do you still think it's valid it to make claims about how semantically similar two docs/toks are? Some people seem to prefer Euclidian distance over cosine similarity.
> 2. `doc.vector` should give me the vector representation of the whole document, right? Which measure is behind the vector returned? Is this e.g. the mean of all the token vectors in the doc? And if I want to lump together a couple of documents to get a vector representation for the whole bunch, is it valid to take the mean of the document vectors or would you recommend a different measure?
> 3. Is it possible to retrieve the n closest neighbour tokens/documents of a target tok/doc?

@wuqui press shift + Tab on ```doc.similarity(doc1)``` in jupyter it shows this
```
Docstring:
Make a semantic similarity estimate. The default estimate is cosine
similarity using an average of word vectors.

other (object): The object to compare with. By default, accepts `Doc`,
    `Span`, `Token` and `Lexeme` objects.
RETURNS (float): A scalar similarity score. Higher is more similar.

DOCS: https://spacy.io/api/doc#similarity
Type:      builtin_function_or_method
```

**Comment by wuqui** [comment]
Thanks for your answer. I had somehow overlooked this, if it was already there back then.

The deeper issues of how good these cosine scores are for making valid and reliable judgements about the semantic similarity between documents still remains controversial, but I guess this is rather a general question for (computational) linguists to deal with.

The third point -- an option to easily retrieve the n most similar words -- would still be nice, I think. I think it would be useful for quite a couple of use cases and for evaluating whether the embeddings are meaningful at all.

**Comment by svlandeg** [comment]
> The third point -- an option to easily retrieve the n most similar words -- would still be nice, I think. I think it would be useful for quite a couple of use cases and for evaluating whether the embeddings are meaningful at all.

This is not supported out of the box, but should be straightforward to implement yourself, cf. also https://stackoverflow.com/questions/57697374/list-most-similar-words-in-spacy-in-pretrained-model.
