### ISSUE TITLE
Textcat - exclusive_classes = False parameter does not seem to work

### ISSUE THREAD

**Issue by pbakhtin** [explosion/spacy-transformers#77]
Hi! Absolutely love Prodigy, Spacy and Spacy Pytorch!

However, I've been testing textcat with SciBERT to classify research papers and ran into a problem, that regardless of my changes to "exclusive_classes" parameter I still get results of categories that add up to 1.

```
nlp = PyTT_Language(pytt_name=name, meta={"lang": "en"})
nlp.add_pipe(nlp.create_pipe("sentencizer"))
nlp.add_pipe(PyTT_WordPiecer.from_pretrained(nlp.vocab, path))
nlp.add_pipe(PyTT_TokenVectorEncoder.from_pretrained(nlp.vocab, path))

print(nlp.pipe_names)
print(f"Loaded model '{name}'")
textcat = nlp.create_pipe(
    "pytt_textcat",
    config={"architecture": "softmax_last_hidden", "words_per_batch": max_wpb, "exclusive_classes": False}
)
```

Results:
`Machine learning (ML) is the scientific study of algorithms and statistical models that computer systems use to perform a specific task without using explicit instructions, relying on patterns and inference instead. It is seen as a subset of artificial intelligence. Machine learning algorithms build a mathematical model based on sample data, known as "training data", in order to make predictions or decisions without being explicitly programmed to perform the task.[1][2]:2 Machine learning algorithms are used in a wide variety of applications, such as email filtering and computer vision, where it is difficult or infeasible to develop a conventional algorithm for effectively performing the task. {'computer science': 0.8130398988723755, 'engineering': 0.15107111632823944, 'chemistry': 0.03588902950286865}`

This is an example of training data (also tried with True / False and removing False categories completely, nothing helps):
`('In this paper, we review the definition and basic properties of the different types of fuzzy sets that have appeared up to now in the literature. We also analyze the relationships between them and enumerate some of the applications in which they have been used.', {'computer science': 1.0, 'engineering': 1.0, 'chemistry': 0.0})`

@honnibal , would you please have a quick look?

Thanks in advance!

Best wishes,

Pavel

**Comment by aatimofeev** [comment]
I've run into the same issue recently.

**Comment by pbakhtin** [comment]
I guess it must be because of Softmax, however other activation functions seem not to be supported at the moment :(

**Comment by pbakhtin** [comment]
I seem to have found a workaround (thanks to #60 ): to add custom architecture based on Sigmoid and use it:

```
from spacy_pytorch_transformers.model_registry import register_model, get_pytt_last_hidden, flatten_add_lengths
from thinc.api import layerize, chain
from thinc.t2v import Pooling, mean_pool
from thinc.v2v import Affine, Model


@register_model("sigmoid_last_hidden")
def sigmoid_last_hidden(nr_class, *, exclusive_classes=False, **cfg):
    width = cfg["token_vector_width"]
    return chain(
        get_pytt_last_hidden,
        flatten_add_lengths,
        Pooling(mean_pool),
        Affine(nr_class, width, drop_factor=0.0),
        logistic
    )


@layerize
def logistic(X, drop=0.0):
    ops = Model.ops
    y = 1.0 / (1.0 + ops.xp.exp(-X))

    def backward(dy, sgd=None):
        return dy * y * (1 - y)

    return y, backward
```

**Comment by nsorros** [comment]
Run into the same issue and this worked @pbakhtin. For future people that run into this problem, notice that the learning rate could go a bit lower than the default for fine tuning to work, e.g. 1e-5.

@honnibal i am happy to open a PR (or for @pbakhtin) introducing this to the library to support textcat with exclusive classes. would that be of interest?

**Comment by sarim-zafar** [comment]
Even after adding the above code, I am getting "KeyError: 'Model sigmoid_last_hidden not found in registry. Available names: affine_output, precomputable_maxout, softmax_class_vector, softmax_last_hidden, softmax_pooler_output, softmax_tanh_class_vector, tensor_affine_tok2vec, tok2vec_per_sentence'"

**Comment by nsorros** [comment]
> @pbakhtin Even after adding the above code, I am getting "KeyError: 'Model sigmoid_last_hidden not found in registry. Available names: affine_output, precomputable_maxout, softmax_class_vector, softmax_last_hidden, softmax_pooler_output, softmax_tanh_class_vector, tensor_affine_tok2vec, tok2vec_per_sentence'"

Where are you adding the code? Two things that worked for me is to fork the library and do the change, then install the library from your forked copy. And adding this in the same file I am writing the training loop. Notice that some functions have changed name
```
@register_model("sigmoid_last_hidden")
def sigmoid_last_hidden(nr_class, *, exclusive_classes=False, **cfg):
    width = cfg["token_vector_width"]
    return chain(
        get_last_hidden,
        flatten_add_lengths,
        Pooling(mean_pool),
        zero_init(Affine(nr_class, width, drop_factor=0.0)),
        logistic,
    )
```
