### ISSUE TITLE
Integrate pretrained multilingual BERT model

### ISSUE THREAD

**Issue by lutz-100worte** [explosion/spacy-transformers#81]
There is a pretrained multilingual BERT model ([`bert-base-multilingual`](https://huggingface.co/transformers/pretrained_models.html?highlight=bert-base-multilingual-cased), provided [by Google](https://github.com/google-research/bert/blob/master/multilingual.md)) available in Huggingface's `transformers` library.

It would be good to have `bert-base-multilingual` integrated in `spacy-transformers`, as well.

**Comment by ines** [comment]
If a (PyTorch) model is supported out-of-the-box by `transformers`, you should be able to use it out-of-the-box in `spacy-transformers`. We provide a few pre-packaged models as examples, but you can build your own using any other pretrained weights.

See the `init_model` script for an example: https://github.com/explosion/spacy-transformers/blob/master/examples/init_model.py

The following worked for me (I'm using the `xx` base language to initialize it as a multi-language model):

```bash
python examples/init_model.py --lang xx --name bert-base-multilingual-cased /path/to/model
```

You can then run `spacy.load("/path/to/model")` or use `spacy package` to create a pip-installable model package.

**Comment by wavymazy** [comment]
Hey @ines,

I was trying to load the [camembert-base](https://huggingface.co/camembert-base) transformer model using the script you provided but couldn't. 

I get the error : Model name 'camembert-base' was not found in model name list

Is there another way to load the model using spacy-transformers ?

Thanks.
