### ISSUE TITLE
Problems with newest Spacy-Transformers

### ISSUE THREAD

**Issue by mmy12580** [explosion/spacy-transformers#82]
I am trying yesterday updated version of spacy transformers, and I would like to apply transfer learning on the distilled version of BERT. I tried the `train_textcat.py` for IMDB sentiment analysis. However, it gives me error like this. The format of `texts` and `annotations` are exactly from the same the textcat tutorial scripts. **spacy_pytorch_transfomers** do not have this problem, while **spacy_transformers** has this problem. May I feel it is good to let you know.

```
Traceback (most recent call last):
  File "train.py", line 207, in <module>
    trainer.train(Config)
  File "train.py", line 49, in train
    self.train_by_batch(config)
  File "train.py", line 105, in train_by_batch
    nlp.update(texts, annotations, sgd=optimizer, drop=0.1, losses=losses)
  File "/home/darktower/.local/lib/python3.6/site-packages/spacy_transformers/language.py", line 98, in update
    tok2vec.set_annotations(docs, outputs)
  File "/home/darktower/.local/lib/python3.6/site-packages/spacy_transformers/pipeline/tok2vec.py", line 198, in set_annotations
    doc.tensor[i] = wp_weighted[word_piece_slice].sum(0)
  File "cupy/core/core.pyx", line 1185, in cupy.core.core.ndarray.__getitem__
  File "cupy/core/_routines_indexing.pyx", line 31, in cupy.core._routines_indexing._ndarray_getitem
  File "cupy/core/_routines_indexing.pyx", line 204, in cupy.core._routines_indexing._prepare_slice_list
IndexError: too many indices for array
```

**Comment by honnibal** [comment]
Thanks, we'll look into this. It looks like the problem was introduced here: https://github.com/explosion/spacy-transformers/pull/67

I think it probably is just missing a check `if word_piece_slice`.

**Comment by mmy12580** [comment]
Thanks for your response sincerely. However, it is not solving the case as you suggested. As you can see the problem is `IndexError` for code 
```
doc.tensor[i] = wp_weighted[word_piece_slice].sum(0)
```
`wp_weighted` is a cupy array with shape, for example, (236, 768). If `word_piece_slice` is a general list for example [1,3,7] or even None, slicing from cupy array should be all good, but the error is too many indices for array. I am not sure if it is dependency problem from copy or not. Therefore, I leveraged Google Colab which I assume it has quite empty environment to do the same thing, and it came with same errors. If you are interested, the sharable link I posted is at https://colab.research.google.com/drive/1GbSflIMPFsijR67Mni_OneckvxUgR0Ws. Again, thanks for your help.

**Comment by tylerjthomas9** [comment]
> 
> 
> Thanks for your response sincerely. However, it is not solving the case as you suggested. As you can see the problem is `IndexError` for code
> 
> ```
> doc.tensor[i] = wp_weighted[word_piece_slice].sum(0)
> ```
> 
> `wp_weighted` is a cupy array with shape, for example, (236, 768). If `word_piece_slice` is a general list for example [1,3,7] or even None, slicing from cupy array should be all good, but the error is too many indices for array. I am not sure if it is dependency problem from copy or not. Therefore, I leveraged Google Colab which I assume it has quite empty environment to do the same thing, and it came with same errors. If you are interested, the sharable link I posted is at https://colab.research.google.com/drive/1GbSflIMPFsijR67Mni_OneckvxUgR0Ws. Again, thanks for your help.

I added a comma to the index of wp_weighted to show that we are indexing the rows over all columns, and it seemed to fix the IndexError. 

`doc.tensor[i] = wp_weighted[word_piece_slice, ].sum(0)`

**Comment by JulianGerhard21** [comment]
Hi,

I can confirm that @tylerjthomas9 's hotfix works for me too.

Regards

**Comment by nsorros** [comment]
I can also confirm it works for me 👍

**Comment by rollator3000** [comment]
I also recieved this error!
Are there any updates to this or do we have to adapt code in "tok2vec.py" according to @tylerjthomas9?

Cheers Frederik

**Comment by honnibal** [comment]
Sorry for letting this slip. We were travelling to PyCon India when this was reported, and I didn't realise we hadn't pushed out the fix yet :(. It should be up today.

**Comment by honnibal** [comment]
Okay, should be up now.
