### ISSUE TITLE
Why is `clean_extended_unicode`  required in XLNetTokenizer?

### ISSUE THREAD

**Issue by tamuhey** [explosion/spacy-transformers#87]
https://github.com/explosion/spacy-transformers/blob/378d6aa9c33acaf8970e607733b85f83bf8a61f5/spacy_transformers/_tokenizers.py#L412

Is this line required?  
This lines remove all non-ascii characters, so for example in Japanese, most characters are lost and it affects wordpiece.

**Comment by honnibal** [comment]
The alignment algorithm is here: https://github.com/explosion/spacy-transformers/blob/378d6aa9c33acaf8970e607733b85f83bf8a61f5/spacy_transformers/pipeline/wordpiecer.py#L108

This function should only be impacting the alignment, not the wordpieces used for prediction. I'd welcome improvements to the code if you can suggest some --- the processing is slow and I feel like better alignment could be achieved with more time spent.

**Comment by tamuhey** [comment]
Thanks for your reply!
I think `clean_extended_unicode` used in XLNet wordpiecer is intended to remove the sentence piece's control character `\u2581`. 
If so, this line should be replaced with the following line:
```python
text = text.replace("\u2581", "")
```

**Comment by ines** [comment]
If I remember correctly, there were a bunch of other unicode characters that were common in our test data (invisible control characters etc.) that the tokenizer wasn't handling properly and that ended up being converted into *other* characters, which made the alignment super difficult.

Here's the script we used to test the alignment: https://github.com/explosion/spacy-transformers/blob/master/examples/test_wordpiece_alignment.py Running this script with the full dataset should ideally pass and not turn up any mismatches with the given alignment rules.

**Comment by tamuhey** [comment]
I created an alignment library for this purpose. https://github.com/tamuhey/tokenizations
