### ISSUE TITLE
Consistency of similarity scores

### ISSUE THREAD

**Issue by atillaguzel** [explosion/spacy-transformers#9]
I have applied similarity function after loading xlnet and bert. It looks score readings for respective models varies significantly. Bert scores feels reliable whereas xlnet fell short of capturing dissimilarity between "Apple" brand and "apple" fruit. I have used exactly the same snippet given in the README file of this project and then a couple of other examples as well. I'm wondering whether everything is fine with spacy's xlnet implementation or maybe I'm just missing something.

**Comment by NirantK** [comment]
Hey @atillaguzel - this is a challenge which I've seen when using the underlying PyTorch Transformers too. 

And from what I understand right now - this is a function of how XLNet and BERT are trained. Both of these techniques implicitly assume long sequence lengths (10-20 tokens or more) - but XLNet is more sensitive to shorter sequence lengths.

**Comment by honnibal** [comment]
@atillaguzel It could be as @NirantK says, but it's also possible there's a bug in the way we're preprocessing for XLNet. There are a lot of details to get right, and we're still in the process of making sure our results are correct.

At the moment I'm working on getting the Glue results from the library to match what `pytorch-transformers` is giving, for all the different models. Once that's finished we'll have more confidence that the processing is correct.

**Comment by svlandeg** [comment]
I think this can be closed after the rewrite and recent publication of v1.0.

New bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions)!
