### ISSUE TITLE
Fine-tuning BERT on lengthy documents

### ISSUE THREAD

**Issue by vr25** [explosion/spacy-transformers#90]
Hi,

I am trying to fine-tune BERT on my task which involves lengthy documents with length ~100,000 tokens. After reading the blog-post on [spacy-transformers](https://explosion.ai/blog/spacy-transformers) and its feature on `batch` ing documents, I was wondering if it is a good idea to use this feature on such lengthy documents.

Thanks.

**Comment by svlandeg** [comment]
Hi, that's kind of difficult to judge up-front, but you may run into memory issues because of the length of the documents. See also Issue #48.
