### ISSUE TITLE
Need more clarification on "subbatching"

### ISSUE THREAD

**Issue by vr25** [explosion/spacy-transformers#91]
`In order to further improve efficiency and reduce memory requirements, spacy-transformers also performs length-based subbatching internally. The subbatching regroups the batched sentences by sequence length, to minimise the amount of padding required. `

The above snippet is from the documentation. I was wondering if subbatching preserves the order of sentences in the document since it regroups internally within the batched sentences.

Thanks.

**Comment by honnibal** [comment]
The output order should be the same, yes. But the sentences are predicted in a different order , because they're regrouped by length.
