### ISSUE TITLE
pre-training from scratch using spacy-transformers

### ISSUE THREAD

**Issue by vr25** [explosion/spacy-transformers#93]
Hi,

I am trying to pre-train BERT kind of model on my dataset (not fine-tune) from scratch; similar to SciBERT, BioBERT, etc. I couldn't find any scripts like run_pretraining.py (pytorch-transformers) in this repo and so I was wondering if this is supported yet or not.

Thanks.

**Comment by svlandeg** [comment]
You could see this library more as a wrapper around already pretrained BERT-like models. You can create a pretrained model from scratch with HF transformers and then use that in a spaCy pipeline. Alternatively, spaCy also has its own version of a pretraining command.  You can find more information here: https://nightly.spacy.io/usage/embeddings-transformers

We've recently published v.1.0 of this library and will release the corresponding spaCy v3.0 soon as well. We'll move support to the spaCy repo. New bugs can be opened on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues) and feature requests or ask for coding help can be posted on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions)!
