### ISSUE TITLE
Ordering for bert vs. roberta in util.get_segment_ids()

### ISSUE THREAD

**Issue by adrianeboyd** [explosion/spacy-transformers#96]
I noticed that `"roberta"` is not going to work here:

https://github.com/explosion/spacy-transformers/blob/61ed043c72e43bd2504d1525e9ec5544870d2c25/spacy_transformers/util.py#L274-L283

**Comment by pmbaumgartner** [comment]
It looks like there were other functions (like `get_model`) that they noticed this issue and addressed it by putting `roberta` first. I made a PR to use `name.startswith({model})`, which should mean that as long as the transformers library keeps consistent with their API and naming conventions, they can order them in whatever way they want and they should always reference the right model.

**Comment by honnibal** [comment]
Thanks Peter!
